const { app } = require('@azure/functions');
const { EmailClient } = require("@azure/communication-email");
const crypto = require('crypto');

// Ensure global.crypto is available for Azure SDKs
if (typeof global.crypto === 'undefined') {
    global.crypto = {
        randomUUID: () => crypto.randomUUID()
    };
}

app.http('SendContactEmail', {
    methods: ['POST'],
    authLevel: 'anonymous',
    handler: async (request, context) => {
        context.log(`Processing contact form submission...`);

        try {
            const body = await request.json();
            const { name, email, phone, message } = body;

            context.log(`Form data received: ${JSON.stringify({ name, email, phone })}`);

            const connectionString = process.env.COMMUNICATION_SERVICES_CONNECTION_STRING;
            const senderAddress = process.env.SENDER_EMAIL_ADDRESS;

            if (!connectionString || !senderAddress) {
                const missing = [];
                if (!connectionString) missing.push("CONNECTION_STRING");
                if (!senderAddress) missing.push("SENDER_ADDRESS");
                context.error(`Missing configuration: ${missing.join(", ")}`);
                return { status: 500, jsonBody: { success: false, message: `Server configuration error: Missing ${missing.join(", ")}` } };
            }
            
            const emailClient = new EmailClient(connectionString);

            const emailMessage = {
                senderAddress: senderAddress,
                content: {
                    subject: `AEIS Inquiry from ${name || 'Website User'}`,
                    plainText: `A new contact form submission has been received from the AEIS website.\n\n` +
                               `DETAILS:\n` +
                               `Name: ${name || 'N/A'}\n` +
                               `Email: ${email || 'N/A'}\n` +
                               `Phone: ${phone || 'N/A'}\n\n` +
                               `MESSAGE:\n${message || 'No message provided.'}`,
                    html: `
                        <div style="font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e6ed; border-radius: 8px; overflow: hidden;">
                            <div style="background-color: #00244d; padding: 20px; color: #ffffff; text-align: center;">
                                <h2 style="margin: 0; font-size: 20px;">New Website Inquiry</h2>
                            </div>
                            <div style="padding: 30px; line-height: 1.6; color: #334155;">
                                <p style="margin-top: 0;">You have received a new message through the <strong>Ambica Electric & Instrument Services</strong> website contact form.</p>
                                
                                <table style="width: 100%; border-collapse: collapse; margin: 25px 0;">
                                    <tr>
                                        <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; font-weight: bold; width: 100px;">Name:</td>
                                        <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9;">${name || 'N/A'}</td>
                                    </tr>
                                    <tr>
                                        <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; font-weight: bold;">Email:</td>
                                        <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9;"><a href="mailto:${email}" style="color: #0099d4; text-decoration: none;">${email || 'N/A'}</a></td>
                                    </tr>
                                    <tr>
                                        <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9; font-weight: bold;">Phone:</td>
                                        <td style="padding: 10px 0; border-bottom: 1px solid #f1f5f9;"><a href="tel:${phone}" style="color: #0099d4; text-decoration: none;">${phone || 'N/A'}</a></td>
                                    </tr>
                                </table>
                                
                                <div style="background-color: #f8fafc; padding: 20px; border-radius: 6px; border-left: 4px solid #0099d4;">
                                    <p style="margin-top: 0; font-weight: bold; color: #1e293b;">Message:</p>
                                    <p style="margin-bottom: 0; white-space: pre-wrap;">${message || 'No message provided.'}</p>
                                </div>
                            </div>
                            <div style="background-color: #f1f5f9; padding: 15px; text-align: center; font-size: 12px; color: #64748b;">
                                This email was automatically generated by the AEIS Website Contact Form.
                            </div>
                        </div>
                    `
                },
                recipients: {
                    to: [{ address: "aeis_india@yahoo.co.in" }]
                },
                replyTo: email ? [{ address: email }] : []
            };

            context.log(`Sending email from ${senderAddress} to aeis_india@yahoo.co.in (Reply-To: ${email})...`);
            const poller = await emailClient.beginSend(emailMessage);
            const result = await poller.pollUntilDone();

            if (result.status === "Succeeded") {
                context.log(`Email sent successfully! ID: ${result.id}`);
                return { status: 200, jsonBody: { success: true, message: "Email sent successfully" } };
            } else {
                context.error(`Email sending failed with status: ${result.status}`);
                return { status: 500, jsonBody: { success: false, message: `Failed to send email. Status: ${result.status}` } };
            }
            
        } catch (error) {
            context.error(`Exception caught: ${error.message}`);
            return { status: 500, jsonBody: { success: false, message: error.message, detail: error.stack } };
        }
    }
});
